(() => {
  const app = document.querySelector('#app');
  const nav = document.querySelector('#navigation');
  const menu = document.querySelector('#menuButton');
  const services = ['Dumpster rental','Stump grinding','Mobile welding','Camper & RV repair','Septic pumping','Driveway grading','Drywall','Roofing','Painting','Flooring','Excavation','Mobile equipment repair','Snow plowing','Landscaping','Tree removal','Plumbing'];
  const sourceTypes = ['Maine state and municipal procurement','School and university facilities postings','Town and city bid notices','Verified public project sources'];
  const esc = (value='') => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const button = (text, href) => `<a class="button" href="${href}">${text}</a>`;
  const serviceCards = () => services.map(x => `<a class="service-card" href="#services?q=${encodeURIComponent(x)}"><span>${x}</span><span class="arrow">→</span></a>`).join('');

  function home(){return `
    <section class="hero" id="home"><p class="eyebrow">MAINE'S LOCAL OPPORTUNITY NETWORK</p><h1>Find reliable help.<br>Build a stronger local business.</h1><p class="lead">One place for customers, independent contractors, mobile service businesses, local job leads and public opportunities—from Bangor to Portland and the communities in between.</p>
      <form class="search-card" id="homeSearch"><div class="field"><label for="homeQ">What do you need?</label><input id="homeQ" placeholder="Example: driveway grading"></div><div class="field"><label for="homeZip">ZIP code</label><input id="homeZip" inputmode="numeric" maxlength="5" placeholder="04401"></div><button class="button">Search within 60 miles</button></form><p class="notice">Use one field or both. Results will automatically use a 60-mile service range once verified businesses are added.</p></section>
    <section class="section soft"><div class="heading-row"><div><p class="eyebrow">SERVICES THAT MOVE WITH MAINE</p><h2>Built for the work that happens on-site.</h2></div><a class="text-link" href="#services">Browse every category →</a></div><div class="service-grid">${serviceCards()}</div></section>
    <section class="section"><p class="eyebrow">HOW IT WORKS</p><h2>Less chasing. Better information.</h2><div class="steps"><article class="step"><span class="step-number">1</span><h3>Search locally</h3><p>Enter a ZIP code and service. Matching businesses are limited to their 60-mile service area.</p></article><article class="step"><span class="step-number">2</span><h3>Choose with confidence</h3><p>Compare available businesses, services, verified reviews, price level and direct contact details.</p></article><article class="step"><span class="step-number">3</span><h3>Post a serious job</h3><p>Share the scope, photos, timing and budget so only fitting contractors receive the opportunity.</p></article></div></section>
    <section class="section opportunity-band"><div><p class="eyebrow">OPPORTUNITY NETWORK</p><h2>See public projects and contract opportunities in one place.</h2><p>We are building a transparent, source-linked feed of current work opportunities for Maine small businesses.</p>${button('Explore opportunities','#opportunities')}</div><ul>${sourceTypes.map(x=>`<li>${x}</li>`).join('')}</ul></section>
    <section class="section story" id="story"><p class="eyebrow">OUR STORY</p><h2>Small business should not disappear just because the work slows down.</h2><p>For years, we worked as small contractors for different companies. We saw good people fall into slow weeks and lose work—not because of poor service, but because advertising, visibility and steady opportunities were out of reach.</p><p>Maine Mobil Connection exists to cut through that hassle. We give local service businesses a practical way to be found, and give customers clear information to choose help with confidence. Our promise is simple: keep improving the information, keep the process reasonable, and support the Maine businesses doing the work.</p></section>`}

  function servicesPage(){ const args=new URLSearchParams(location.hash.split('?')[1]||'');const q=args.get('q')||'';const zip=args.get('zip')||'';const matches=services.filter(x=>x.toLowerCase().includes(q.toLowerCase()));return `<section class="page"><a class="back" href="#home">← Maine Mobil Connection</a><p class="eyebrow">LOCAL SERVICE DIRECTORY</p><h1>Find services near you.</h1><p>Search by service, a ZIP code, or both. Businesses will appear here only after their public listing is approved.</p><form class="filter-bar" id="directorySearch"><input name="q" value="${esc(q)}" placeholder="Any service"><input name="zip" value="${esc(zip)}" maxlength="5" inputmode="numeric" placeholder="ZIP code"><button class="button">Search</button></form><p class="notice">${zip?`Searching within 60 miles of ${esc(zip)}.`:'Enter a ZIP code to use the 60-mile radius.'}</p><div class="empty"><h2>No verified business listings found yet.</h2><p>We will show every matching local business in this area as verified listings are added. ${button('Create a contractor profile','#account')}</p></div><h2 style="margin-top:2.5rem">${q?'Matching service categories':'Browse service categories'}</h2><div class="service-grid">${(matches.length?matches:services).map(x=>`<a class="service-card" href="#post-job?service=${encodeURIComponent(x)}"><span>${x}</span><span class="arrow">Request a job →</span></a>`).join('')}</div></section>`}

  function opportunities(){return `<section class="page"><a class="back" href="#home">← Maine Mobil Connection</a><p class="eyebrow">PUBLIC WORK OPPORTUNITIES</p><h1>Work worth finding.</h1><p>This page will list current, source-linked public opportunities in the Maine service area. We will not present scraped or unverified information as a live contract.</p><div class="source-list"><h2>Sources being connected</h2>${sourceTypes.map(x=>`<p>• ${x}</p>`).join('')}</div><div class="empty"><h2>Opportunity feed is being verified.</h2><p>Every listing will show a source, deadline, location, last-checked time and direct link before contractors can act on it.</p></div>${button('Create contractor account','#account')}</section>`}

  function postJob(){const args=new URLSearchParams(location.hash.split('?')[1]||'');const preset=args.get('service')||'';return `<section class="page"><a class="back" href="#home">← Maine Mobil Connection</a><p class="eyebrow">SERIOUS JOB REQUEST</p><h1>Tell contractors what you need.</h1><p>Photos, a clear scope, timing and a realistic budget help serious requests reach the right local businesses.</p><form class="form-card" id="jobForm"><div class="two-col"><div class="field"><label>Job title</label><input name="title" required placeholder="Example: Regrade gravel driveway"></div><div class="field"><label>Service category</label><select name="service">${services.map(x=>`<option ${x===preset?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="field"><label>Job ZIP code</label><input name="zip" maxlength="5" inputmode="numeric" required placeholder="04401"></div><div class="field"><label>Describe the work</label><textarea name="description" required placeholder="Include measurements, access, materials, condition and any important details."></textarea></div><div class="two-col"><div class="field"><label>Preferred timing</label><select name="timing"><option>As soon as possible</option><option>Within 2 weeks</option><option>Within 1 month</option><option>Planning ahead</option></select></div><div class="field"><label>Budget range</label><select name="budget"><option>Not sure yet</option><option>Under $500</option><option>$500–$2,000</option><option>$2,000–$10,000</option><option>Over $10,000</option></select></div></div><div class="field"><label>Photos</label><input type="file" accept="image/*" multiple disabled><span class="notice">Photo uploads activate with the production account database.</span></div><label><input type="checkbox" required> I am serious about hiring and the details above are accurate.</label><button class="button">Create account to submit</button><div class="status" id="jobStatus"></div></form></section>`}

  function dealers(){return `<section class="page"><a class="back" href="#home">← Maine Mobil Connection</a><p class="eyebrow">TOOLS, EQUIPMENT & PARTS</p><h1>Find local dealers and suppliers.</h1><p>Large brands and local dealers will be searchable here, while the contractor side of the network stays focused on independent small businesses.</p><div class="empty"><h2>Dealer directory is being built.</h2><p>Authorized dealers, equipment rental, tool supply and parts sources will be added with their location, brands and contact details.</p></div></section>`}

  function reviews(){return `<section class="page"><a class="back" href="#home">← Maine Mobil Connection</a><p class="eyebrow">VERIFIED JOB REVIEWS</p><h1>Real work deserves real feedback.</h1><p>Reviews will only be available after a job is marked completed through Maine Mobil Connection. Customers can rate communication, workmanship, fairness of pricing and final job cost up to 5.5.</p><div class="card-grid"><article class="info-card review-card"><span class="stars">★★★★★+</span><strong>Verified only</strong><p>No anonymous review pile-on. A completed platform job is required.</p></article><article class="info-card review-card"><span class="stars">$ to $$$$</span><strong>Pricing context</strong><p>Customers can say whether pricing felt fair and where it fell on the price range.</p></article><article class="info-card review-card"><span class="stars">5.5 max</span><strong>Clear standard</strong><p>Businesses build trust one completed job at a time.</p></article></div></section>`}

  function account(){return `<section class="page"><a class="back" href="#home">← Maine Mobil Connection</a><p class="eyebrow">ACCOUNT ACCESS</p><h1>Join the network.</h1><p>Use a customer account to post and manage a job. Use a contractor account to create a shareable business card, manage your profile, receive selected opportunities and submit bids.</p><div class="two-col"><form class="form-card" id="customerForm"><h2>Customer account</h2><div class="field"><label>Email</label><input type="email" required placeholder="you@email.com"></div><button class="button">Create customer account</button></form><form class="form-card" id="contractorForm"><h2>Contractor account</h2><div class="field"><label>Business name</label><input required placeholder="Your business name"></div><div class="field"><label>Email</label><input type="email" required placeholder="you@business.com"></div><button class="button">Create contractor account</button></form></div><div class="status" id="accountStatus"></div><p class="notice">Live sign-up and confirmation emails activate after the business-owned Supabase account is connected. No test accounts or fake business listings will appear in production.</p></section>`}

  function render(){const page=(location.hash||'#home').slice(1).split('?')[0];const view={home,services:servicesPage,opportunities,'post-job':postJob,dealers,reviews,account,story:home}[page]||home;app.innerHTML=view();bind();window.scrollTo({top:0,behavior:'instant'});}
  function bind(){document.querySelector('#homeSearch')?.addEventListener('submit',e=>{e.preventDefault();const q=document.querySelector('#homeQ').value;const zip=document.querySelector('#homeZip').value;location.hash=`services?q=${encodeURIComponent(q)}&zip=${encodeURIComponent(zip)}`});document.querySelector('#directorySearch')?.addEventListener('submit',e=>{e.preventDefault();const form=new FormData(e.currentTarget);location.hash=`services?q=${encodeURIComponent(form.get('q'))}&zip=${encodeURIComponent(form.get('zip'))}`});document.querySelector('#jobForm')?.addEventListener('submit',e=>{e.preventDefault();const status=document.querySelector('#jobStatus');status.textContent='Account and photo storage setup is required before this job can be submitted. Your details were not sent.';status.classList.add('show')});['customerForm','contractorForm'].forEach(id=>document.querySelector('#'+id)?.addEventListener('submit',e=>{e.preventDefault();const status=document.querySelector('#accountStatus');status.textContent='Account sign-up will turn on as soon as the business-owned Supabase project is connected. No information was submitted.';status.classList.add('show')}));}
  menu.addEventListener('click',()=>nav.classList.toggle('open'));window.addEventListener('hashchange',render);render();
})();
